version: '2'
services:

  postgres:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME:
#      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - ./volume/mongo/data:/data/db
